(defvar my-packages 
  '(
    ace-jump-mode
    ace-window
    ag
    auto-complete-exuberant-ctags
    better-defaults
    comment-dwim-2
    dropdown-list
    etags-select
    find-file-in-project
    flycheck-irony
    haskell-mode
    helm-ag
    helm-projectile
    idle-highlight-mode
    ido-ubiquitous
    irony
    magit
    paredit
    smooth-scrolling
    undo-tree
    win-switch
    yasnippet
    zenburn-theme
))
