(defvar my-packages 
  '(
    ag
    auto-complete-exuberant-ctags
    better-defaults
    comment-dwim-2
    dropdown-list
    etags-select
    find-file-in-project
    haskell-mode
    helm-ag
    helm-projectile
    idle-highlight-mode
    ido-ubiquitous
    magit
    paredit
    win-switch
    yasnippet
    zenburn-theme
))
