(load "package-list.el")
(load "load-packages.el")
(load "settings.el")
(load "python-mode-config.el")
(load "cc-mode-config.el")
(load "win-switch-config.el")
(load "haskell-config.el")
(load "yasnippet-config.el")
(load "key-bindings.el")

