(load-theme 'zenburn)
(ido-mode 0)
(helm-mode)
(set 'ring-bell-function 'ignore)
(set 'compilation-scroll-output 'first-error)
(defalias 'yes-or-no-p 'y-or-n-p)
(set 'kill-whole-line t)
(global-undo-tree-mode t)
(set 'magit-last-seen-setup-instructions "1.4.0")
